apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base_infra
  namespace: argo
spec:
  source:
    repoURL: https://github.com/bobzhangwz/argo-deployment.git
    targetRevision: HEAD
    path: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
