apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-infra
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/bobzhangwz/argo-deployment.git
    targetRevision: HEAD
    path: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
