repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    chart: argo/argo-cd
    namespace: argo
    createNamespace: true
    secrets:
      - secret.enc.yaml
    values:
      # - ./values/helm-secret-pulgin.yaml
      - redis-ha:
          enabled: false
        controller:
          replicas: 1
        server:
          autoscaling:
            enabled: false
            minReplicas: 1
          config:
            helm.valuesFileSchemes: >-
              secrets+gpg-import, secrets+gpg-import-kubernetes,
              secrets+age-import, secrets+age-import-kubernetes,
              secrets,secrets+literal,
              https
        repoServer:
          autoscaling:
            enabled: false
            minReplicas: 1
        applicationSet:
          replicaCount: 1
        configs:
          cm:
            'kustomize.buildOptions': --enable-helm
          params:
            'server.insecure': true

