apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argo
spec:
  project: default
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    helm:
      releaseName: argocd-image-updater
      values: |
        config:
          argocd:
            grpcWeb: false
            serverAddress: "http://argocd.argo"
            insecure: true
            plaintext: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
