kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: projecta
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  permitOnlyProjectScopedClusters: true
  sourceRepos:
    - '*'
  sourceNamespaces:
    - namespace-one
    - argo
    - helloworld
  destinations:
  - namespace: helloworld
    server: https://kubernetes.default.svc
    name: in-cluster

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  # namespaceResourceBlacklist:
  # - group: ''
    # kind: ResourceQuota
  # - group: ''
    # kind: LimitRange
  # - group: ''
    # kind: NetworkPolicy

  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to project A
    policies:
    - p, proj:projecta:read-only, applications, get, projecta/*, allow
    groups:
    - projecta-readonly

  - name: admin
    description: Admin privileges to projecta
    policies:
      - p, proj:projecta:read-only, applications, get, projecta/*, allow
      - p, proj:projecta:read-only, applications, get, projecta/*, allow
      - p, proj:projecta:read-only, applications, get, projecta/*, allow

      - p, proj:projecta:admin, applications, create, projecta/*, allow
      - p, proj:projecta:admin, applications, update, projecta/*, allow
      - p, proj:projecta:admin, applications, delete, projecta/*, allow
      - p, proj:projecta:admin, applications, sync, projecta/*, allow
      - p, proj:projecta:admin, applications, override, projecta/*, allow
      - p, proj:projecta:admin, applications, action/*, projecta/*, allow

      - p, proj:projecta:admin, applicationsets, get, projecta/*, allow
      - p, proj:projecta:admin, applicationsets, create, projecta/*, allow
      - p, proj:projecta:admin, applicationsets, update, projecta/*, allow
      - p, proj:projecta:admin, applicationsets, delete, projecta/*, allow
      - p, proj:projecta:admin, exec, create, projecta/*, allow
    groups:
    - projecta-admin
