---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-app
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: backstage_img=160071257600.dkr.ecr.ap-northeast-1.amazonaws.com/backstage
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo/static-web-repo
    # https://argocd-image-updater.readthedocs.io/en/stable/basics/update-methods/
    argocd-image-updater.argoproj.io/git-branch: master:image-updater{{range .Images}}-{{.Name}}-{{.NewTag}}{{end}}

    argocd-image-updater.argoproj.io/backstage_img.kustomize.image-name: 160071257600.dkr.ecr.ap-northeast-1.amazonaws.com/backstage
    # argocd-image-updater.argoproj.io/argocd.force-update: true
    argocd-image-updater.argoproj.io/backstage_img.update-strategy: latest
    argocd-image-updater.argoproj.io/backstage_img.ignore-tags: regexp:^DEV$
    # https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/
    argocd-image-updater.argoproj.io/backstage_img.pull-secret: pullsecret:argo/aws-rds-secret
spec:
  source:
    path: deployments/base/
    repoURL: https://github.com/bobzhangwz/backstage-test
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

