---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld-app
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: helloworld_image=160071257600.dkr.ecr.ap-northeast-1.amazonaws.com/static_web
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argo/static-web-repo
    # https://argocd-image-updater.readthedocs.io/en/stable/basics/update-methods/
    argocd-image-updater.argoproj.io/git-branch: master:image-updater{{range .Images}}-{{.Name}}-{{.NewTag}}{{end}}

    argocd-image-updater.argoproj.io/helloworld_image.kustomize.image-name: 160071257600.dkr.ecr.ap-northeast-1.amazonaws.com/static_web
    # argocd-image-updater.argoproj.io/argocd.force-update: true
    argocd-image-updater.argoproj.io/helloworld_image.update-strategy: latest
    argocd-image-updater.argoproj.io/helloworld_image.ignore-tags: regexp:^DEV$
    # https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/
    argocd-image-updater.argoproj.io/helloworld_image.pull-secret: pullsecret:argo/aws-rds-secret
spec:
  project: default
  source:
    path: deployments/prod
    repoURL: https://github.com/bobzhangwz/static-web
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: helloworld
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

