apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
commonLabels:
  type: app
resources: []
  # - ./helloworld_basic.yaml
  # - ./helloworld_app.yaml
  # - ./backstage_app.yaml
generators:
  - ./secret-generator.yaml
